<?php $tab_fav = array (
  'aniki07' => 
  array (
    'cocktail' => 
    array (
      0 => 'Cocktail de fruits au citron vert',
      1 => 'Builder',
      2 => 'Bloody Mary',
      3 => 'Cocktail de fruits au citron vert',
      4 => 'Builder',
      5 => 'Bloody Mary',
      6 => 'Bloody Mary',
      7 => 'Bloody Mary',
      8 => 'Bloody Mary',
      9 => 'Bloody Mary',
      10 => 'Bloody Mary',
      11 => 'Bloody Mary',
      12 => 'Bloody Mary',
      13 => 'Cocktail de fruits au citron vert',
      14 => 'Builder',
      15 => 'Bloody Mary',
      16 => 'Bloody Mary',
      17 => 'Bloody Mary',
      18 => 'Bloody Mary',
      19 => 'Bloody Mary',
      20 => 'Bloody Mary',
      21 => 'Bloody Mary',
      22 => 'Bloody Mary',
      23 => 'Cocktail de fruits au citron vert',
      24 => 'Builder',
      25 => 'Bloody Mary',
      26 => 'Black velvet',
      27 => 'Bloody Mary',
      28 => 'Cocktail de fruits au citron vert',
      29 => 'Builder',
      30 => 'Black velvet',
      31 => 'Bloody Mary',
      32 => 'Cocktail de fruits au citron vert',
      33 => 'Builder',
    ),
  ),
); ?>