<?php $tab_fav = array (
  'aniki07' => 
  array (
    'cocktail' => 
    array (
      0 => 'Frosty lime',
      1 => 'Margarita',
      2 => 'Bora bora',
      3 => 'Alerte %C3%A0 Malibu (cocktail de la couleurs des fameux maillots de bains... ou presque)',
      4 => '',
      5 => '',
      6 => '',
      7 => '',
      8 => '',
      9 => '',
      10 => '',
      11 => '',
      12 => '',
      13 => '',
      14 => '',
      15 => '',
      16 => '',
      17 => 'Frosty lime',
      18 => 'Margarita',
      19 => 'Bora bora',
      20 => 'Alerte %C3%A0 Malibu (cocktail de la couleurs des fameux maillots de bains... ou presque)',
      21 => '',
      22 => '',
      23 => '',
      24 => '',
      25 => '',
      26 => '',
      27 => '',
      28 => '',
      29 => '',
      30 => '',
      31 => '',
      32 => '',
      33 => '',
    ),
  ),
); ?>